#index:
#   path: /
#    controller: App\Controller\DefaultController::index

admin:
        path: /administration
        controller: App\Controller\AdminController::index_admin
genre:
        path: /genre
        controller: App\Controller\AdminController::shoutcastAPI_byGenre


